=== Annabel707/lenguaje-de-marcas/lenguaje de marcas/ejerciciosXML/ejerciciosDTD/ej3.dtd
<!ELEMENT proyectos (proyecto*)>
<!ELEMENT proyecto (nombre,fecha,duracion,empleados?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ATTLIST proyecto prioritario (si|no) #REQUIRED>
<!ELEMENT empleados (empleado,rol)>
<!ELEMENT empleado (#PCDATA)>
<!ELEMENT rol (#PCDATA)>

=== Annabel707/lenguaje-de-marcas/lenguaje de marcas/ejerciciosXML/ejerciciosDTD/ej3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE proyectos SYSTEM "ej3.dtd">
<proyectos>
    <proyecto prioritario="si">
        <nombre></nombre>
        <fecha></fecha>
        <duracion></duracion>
        <empleados>
            <empleado></empleado>
            <rol></rol>
        </empleados>
    </proyecto>
</proyectos>
