=== Annabel707/lenguaje-de-marcas/lenguaje de marcas/ejerciciosXML/ejerciciosDTD/ej5.dtd
<!ELEMENT pedidos (pedido*)>
<!ELEMENT pedido (cliente,nombre,direccion,productos+)>
<!ATTLIST pedido id ID #REQUIRED>
<!ELEMENT cliente (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (calle,ciudad,cp)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT cp (#PCDATA)>
<!ELEMENT productos (producto,precio,cantidad)>
<!ELEMENT producto (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ATTLIST productos id ID #REQUIRED>

=== Annabel707/lenguaje-de-marcas/ejerciciosXML/ejerciciosDTD/ej5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pedidos SYSTEM "ej5.dtd">
<pedidos>
    <pedido id ="p12">
        <cliente></cliente>
        <nombre></nombre>
        <direccion>
            <calle></calle>
            <ciudad></ciudad>
            <cp></cp>
        </direccion>
        <productos id="p4">
            <producto></producto>
            <precio></precio>
            <cantidad></cantidad>
        </productos>
    </pedido>
</pedidos>
