=== Annabel707/lenguaje-de-marcas/lenguaje de marcas/ejerciciosXML/ejerciciosDTD/ej6.dtd
<!ELEMENT listacursos (curso+)>
<!ELEMENT curso (profesores+,contenido)>
<!ATTLIST curso id ID #REQUIRED>
<!ELEMENT profesores (dni,nombre,apellido,segundoapellido?)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT segundoapellido (#PCDATA)>
<!ELEMENT contenido (descripcion,horas,creditos?)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT horas (#PCDATA)>
<!ELEMENT creditos (#PCDATA)>

=== Annabel707/lenguaje-de-marcas/ejerciciosXML/ejerciciosDTD/ej6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listacursos SYSTEM "ej6.dtd">
<listacursos>
    <curso id="c12">
        <profesores>
            <dni></dni>
            <nombre></nombre>
            <apellido></apellido>
            <segundoapellido></segundoapellido>
        </profesores>
        <contenido>
            <descripcion></descripcion>
            <horas></horas>
            <creditos></creditos>
        </contenido>
    </curso>
</listacursos>
