=== Annabel707/lenguaje-de-marcas/lenguaje de marcas/XML/evento.dtd
<!ELEMENT evento (titulo,fecha,ubicacion,pausa,conferenciante)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT ubicacion (#PCDATA)>
<!ELEMENT pausa (nullchar)>
<!ELEMENT conferenciante (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tema (#PCDATA)>

=== Annabel707/lenguaje-de-marcas/XML/evento.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE evento SYSTEM "evento.dtd">
<evento>
    <titulo>EVENTOS MALAGA</titulo>
    <fecha>12/02/2026</fecha>
    <ubicacion>MALAGA</ubicacion>
    <pausa />
    <conferenciante>
        <nombre>Julian</nombre>
        <tema></tema>
    </conferenciante>
    <pausa />
    <conferenciante>
        <nombre></nombre>
        <tema></tema>
    </conferenciante>
</evento>
