=== Annabel707/lenguaje-de-marcas/lenguaje de marcas/ejerciciosXML/ej4.dtd
<!ELEMENT coleccion (albúm*)>
<!ELEMENT albúm (fotografías*)>
<!ELEMENT fotografías (lugar,fecha,tipo,personas,monumento?)>
<!ELEMENT lugar (#PCDATA)>
<!ELEMENT fecha (dia,hora)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT personas (#PCDATA)>
<!ELEMENT monumento (#PCDATA)>

=== Annabel707/lenguaje-de-marcas/ejerciciosXML/ej4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE coleccion SYSTEM "ej4.dtd">
<coleccion>
    <albúm>
    <fotografías>
        <lugar> </lugar>
        <fecha>
            <dia></dia>
            <hora></hora>
        </fecha>
        <tipo></tipo>
        <personas></personas>
        <monumento></monumento>
    </fotografías>
    <fotografías>
        <lugar> </lugar>
        <fecha>
            <dia></dia>
            <hora></hora>
        </fecha>
        <tipo></tipo>
        <personas></personas>
        <monumento></monumento>
    </fotografías>
    <fotografías>
        <lugar> </lugar>
        <fecha>
            <dia></dia>
            <hora></hora>
        </fecha>
        <tipo></tipo>
        <personas></personas>
        <monumento></monumento>
    </fotografías>
    <fotografías>
        <lugar> </lugar>
        <fecha>
            <dia></dia>
            <hora></hora>
        </fecha>
        <tipo></tipo>
        <personas></personas>
        <monumento></monumento>
    </fotografías>
    </albúm>
    <albúm>
    <fotografías>
        <lugar> </lugar>
        <fecha>
            <dia></dia>
            <hora></hora>
        </fecha>
        <tipo></tipo>
        <personas></personas>
        <monumento></monumento>
    </fotografías>
    <fotografías>
        <lugar> </lugar>
        <fecha>
            <dia></dia>
            <hora></hora>
        </fecha>
        <tipo></tipo>
        <personas></personas>
        <monumento></monumento>
    </fotografías>
    <fotografías>
        <lugar> </lugar>
        <fecha>
            <dia></dia>
            <hora></hora>
        </fecha>
        <tipo></tipo>
        <personas></personas>
        <monumento></monumento>
    </fotografías>
    <fotografías>
        <lugar> </lugar>
        <fecha>
            <dia></dia>
            <hora></hora>
        </fecha>
        <tipo></tipo>
        <personas></personas>
        <monumento></monumento>
    </fotografías>
    </albúm>
</coleccion>
