=== Annabel707/lenguaje-de-marcas/ejerciciosXML/ej1.dtd
<!ELEMENT correo (remitente*,destinatario*,asunto*,mensaje*)>
<!ELEMENT remitente (nombre,direccion)>
<!ELEMENT destinatario (nombre,direccion)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT asunto (#PCDATA)>
<!ELEMENT mensaje (#PCDATA)>

=== Annabel707/lenguaje-de-marcas/ejerciciosXML/ej1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE correo SYSTEM "ej1.dtd">

<correo>
<remitente>
    <nombre>     Paco     </nombre>
    <direccion>   ana@gmail.com    </direccion>
</remitente>
<destinatario>
    <nombre>       Ana   </nombre>
    <direccion>     paco@gmail.com  </direccion>
</destinatario>
<asunto>Trabajo </asunto>
<mensaje>Hola, ¿Ana mañana vienes a trabajar?</mensaje>


</correo>
