=== Annabel707/lenguaje-de-marcas/ejerciciosXML/ej3.dtd
<!ELEMENT productos (producto+)>
<!ELEMENT producto (nombre,descripcion,precio,caracteristicas)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT caracteristicas (nombre,valor)>
<!ELEMENT valor (#PCDATA)>

=== Annabel707/lenguaje-de-marcas/ejerciciosXML/ej3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE productos SYSTEM "ej3.dtd">
<productos>
    <producto>
    <nombre> </nombre>
    <descripcion></descripcion>
    <precio></precio>
    <caracteristicas>
        <nombre></nombre>
        <valor></valor>
    </caracteristicas>
</producto>
<producto>
    <nombre> </nombre>
    <descripcion></descripcion>
    <precio></precio>
    <caracteristicas>
        <nombre></nombre>
        <valor></valor>
    </caracteristicas>
</producto>
</productos>
