=== Annabel707/lenguaje-de-marcas/ejerciciosXML/ejerciciosDTD/ej2.dtd
<!ELEMENT canciones (cancion*)>
<!ELEMENT cancion (titulo,duracion,nombre,album,(a単o|compa単ia))>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT album (#PCDATA)>
<!ELEMENT a単o (#PCDATA)>
<!ELEMENT compa単ia (#PCDATA)>
<!ATTLIST cancion genero CDATA #REQUIRED>

=== Annabel707/lenguaje-de-marcas/lenguaje de marcas/ejerciciosXML/ejerciciosDTD/ej2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE canciones SYSTEM "ej2.dtd">
<canciones>
    <cancion genero="rock">
       <titulo></titulo>
       <duracion></duracion>
       <nombre></nombre>
       <album></album>
       <a単o></a単o>
    </cancion>

    <cancion genero="pop">
        <titulo></titulo>
        <duracion></duracion>
        <nombre></nombre>
        <album></album>
        <compa単ia></compa単ia>
     </cancion>
 
</canciones>
