=== Annabel707/lenguaje-de-marcas/ejerciciosXML/ejerciciosDTD/ej7.dtd
<!ELEMENT software (programa+)>
<!ELEMENT programa (titulo,idioma,precio,categoria,descripcion,departamentos+,web?,caratula?)>
<!ATTLIST programa codigo CDATA #REQUIRED>
<!ATTLIST programa version CDATA #REQUIRED>
<!ATTLIST programa año CDATA #IMPLIED>
<!ATTLIST programa sistema CDATA "windows">
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT idioma (español|ingles)>
<!ELEMENT español EMPTY>
<!ELEMENT ingles EMPTY>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT categoria (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT departamentos (#PCDATA)>
<!ELEMENT web (#PCDATA)>
<!ELEMENT caratula (#PCDATA)>

=== Annabel707/lenguaje-de-marcas/ejerciciosXML/ejerciciosDTD/ej7.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE software SYSTEM "ej7.dtd">
<software>
    <programa codigo="1" version="45" año="2005" sistema="linux" > 
        <titulo></titulo>
       <idioma> <español /> </idioma>
        <precio></precio>
        <categoria></categoria>
        <descripcion></descripcion>
        <departamentos></departamentos>
        <web></web>
        <caratula></caratula>
    </programa>
</software>
